### ISSUE TITLE
How to finetune your pretrained model for QA task?  

### ISSUE THREAD

**Issue by mellahysf** [UBC-NLP/araT5#1]
Hi,

Thank you for sharing your great work!

Can you tell me please how to finetune one of your pretrained LM for a Question-Answering (QA) task? 

As input, I have question and context. As output one or multiple answers.

It's very urgent, please!

Thank you so much.

**Comment by mellahysf** [comment]
@Nagoudi @elmadany @mageed any suggestions about this please?

**Comment by Nagoudi** [comment]
Hi @mellahysf,
You can simply follow this  [G colab](https://colab.research.google.com/github/patil-suraj/exploring-T5/blob/master/T5_on_TPU.ipynb#scrollTo=NaGYDvKUe8VS).  The only change you need to do is to upload the AraT5 model and toknizer  instead of T5.
