### ISSUE TITLE
Error while trying the sample code.

### ISSUE THREAD

**Issue by abdullah-saal** [UBC-NLP/araT5#2]
Hello, Thanks for the models.
I was trying to run the provided sample code in the README, but I got the following error:
```
[ValueError: Couldn't instantiate the backend tokenizer from one of: 
(1) a `tokenizers` library serialization file, 
(2) a slow tokenizer instance to convert or 
(3) an equivalent slow tokenizer class to instantiate and convert. 
You need to have sentencepiece installed to convert a slow tokenizer to a fast one.]()
```
any ideas what is the issue?

**Comment by abdullah-saal** [comment]
Closing, just needed to install the required libraries.

**Comment by NoraAlt** [comment]
Could you please share what libraries should be installed? I faced same error.
