### ISSUE TITLE
operative config gin file for arat5 base msa

### ISSUE THREAD

**Issue by nadhem-zmandar** [UBC-NLP/araT5#8]
hello

Where can we find the operative config gin file of  [araT5 Base msa model](https://huggingface.co/UBC-NLP/AraT5-msa-base). It is needed to continue the training of the model using a TPU.

the operative config gin files of the English T5 is available is available in the folder of every pretrained model such as
gs://t5-data/pretrained_models/small/operative_config.gin

Thank you

**Comment by NoraAlt** [comment]
Could you please share where is the operative config file of AraT5?
